/* Generated by tools/i2/gen_admission_envelope.py. Do not edit. */
#pragma once
#include <stdint.h>

#define I2_ADMISSION_CATALOG_COUNT 3u
#define I2_MAX_CHUNK_BYTES 4096u
#define I2_MAX_CHUNKS 32u
#define I2_MAX_STAGE_BYTES 131066u
#define I2_CUE_CACHE_ENTRIES 131072u
#define I2_CUE_CACHE_ADMITTED 98304u
#define I2_FORMULA_CACHE_ENTRIES 131072u
#define I2_FORMULA_CACHE_ADMITTED 98304u
#define I2_COPY_MAP_ENTRIES 131072u
#define I2_COPY_MAP_ADMITTED 98304u
#define I2_JAM_CACHE_ENTRIES 131072u
#define I2_JAM_CACHE_ADMITTED 98304u
#define I2_CUE_MAX_INPUT_BYTES 1048576u
#define I2_CUE_MAX_DEPTH 256
#define I2_CUE_MAX_NODES 131072
#define I2_CUE_MAX_CELLS 65536
#define I2_CUE_MAX_BACKREFS 65536
#define I2_CUE_MAX_ATOM_BYTES 262144u
#define I2_CUE_MAX_TOTAL_ATOM_BYTES 1048576u
#define I2_CUE_MAX_WORK 2000000
#define I2_BSS_RESERVED_BYTES 33554432u
#define I2_BSS_ADMITTED_BYTES 25165824u
#define I2_HISTORICAL_REFUSAL_COUNT 2u

static const uint8_t I2_ADMISSION_ENVELOPE_DIGEST[32] = {
    0xd1, 0x9c, 0xff, 0x01, 0x20, 0xe2, 0x15, 0xf9,
    0x73, 0x4b, 0x1a, 0x99, 0x3f, 0x2f, 0x36, 0x11,
    0xaa, 0x1b, 0xec, 0xe0, 0x69, 0xf1, 0x31, 0x20,
    0xb0, 0x3b, 0x9a, 0xdc, 0x1b, 0x85, 0x9b, 0x89
};

typedef struct {
    const char *catalog_id;
    const char *display_label;
    uint8_t program_hash[32];
    uint8_t executable_anchor[32];
    uint8_t pill_digest[32];
    uint8_t limits_hash[32];
    uint8_t capability_profile;
    uint8_t bootstrap;
    uint32_t pill_bytes;
} i2_admission_catalog_entry_t;
