/* Generated by tools/i2/gen_admission_envelope.py. Do not edit. */
/* Admission profile: ClosedProcessExecutionEnvelope/v2. */
#define I2_ADMISSION_PROFILE_NAME "ClosedProcessExecutionEnvelope/v2"
#pragma once
#include <stdint.h>

#define I2_ADMISSION_CATALOG_COUNT 3u
#define I2_MAX_CHUNK_BYTES 4096u
#define I2_MAX_CHUNKS 32u
#define I2_MAX_STAGE_BYTES 131066u
#define I2_CUE_CACHE_ENTRIES 131072u
#define I2_CUE_CACHE_ADMITTED 98304u
#define I2_FORMULA_CACHE_ENTRIES 131072u
#define I2_FORMULA_CACHE_ADMITTED 98304u
#define I2_COPY_MAP_ENTRIES 131072u
#define I2_COPY_MAP_ADMITTED 98304u
#define I2_JAM_CACHE_ENTRIES 131072u
#define I2_JAM_CACHE_ADMITTED 98304u
#define I2_CUE_MAX_INPUT_BYTES 1048576u
#define I2_CUE_MAX_DEPTH 256
#define I2_CUE_MAX_NODES 131072
#define I2_CUE_MAX_CELLS 65536
#define I2_CUE_MAX_BACKREFS 65536
#define I2_CUE_MAX_ATOM_BYTES 262144u
#define I2_CUE_MAX_TOTAL_ATOM_BYTES 1048576u
#define I2_CUE_MAX_WORK 2000000
#define I2_BSS_RESERVED_BYTES 33554432u
#define I2_BSS_ADMITTED_BYTES 25165824u
#define I2_HISTORICAL_REFUSAL_COUNT 2u

static const uint8_t I2_ADMISSION_ENVELOPE_DIGEST[32] = {
    0x32, 0x73, 0x7f, 0xca, 0x45, 0xbd, 0xf9, 0x39,
    0x2c, 0xc1, 0xa5, 0x75, 0x41, 0x64, 0xfa, 0xf7,
    0xe6, 0xec, 0xbe, 0x2b, 0x21, 0xb0, 0xac, 0x43,
    0x7c, 0x68, 0xd0, 0xdc, 0xcf, 0xbe, 0xcd, 0x73
};

typedef struct {
    const char *catalog_id;
    const char *display_label;
    uint8_t program_hash[32];
    uint8_t executable_anchor[32];
    uint8_t pill_digest[32];
    uint8_t limits_hash[32];
    uint8_t capability_profile;
    uint8_t bootstrap;
    uint32_t pill_bytes;
} i2_admission_catalog_entry_t;
