/* Generated by tools/i2/gen_admission_envelope.py. Do not edit. */
/* Admission profile: M19StaticResource/dev. */
#define I2_ADMISSION_PROFILE_NAME "M19StaticResource/dev"
#pragma once
#include <stdint.h>

#define I2_ADMISSION_CATALOG_COUNT 1u
#define I2_MAX_CHUNK_BYTES 4096u
#define I2_MAX_CHUNKS 32u
#define I2_MAX_STAGE_BYTES 131066u
#define I2_CUE_CACHE_ENTRIES 131072u
#define I2_CUE_CACHE_ADMITTED 98304u
#define I2_FORMULA_CACHE_ENTRIES 131072u
#define I2_FORMULA_CACHE_ADMITTED 98304u
#define I2_COPY_MAP_ENTRIES 131072u
#define I2_COPY_MAP_ADMITTED 65536u
#define I2_JAM_CACHE_ENTRIES 131072u
#define I2_JAM_CACHE_ADMITTED 98304u
#define I2_CUE_MAX_INPUT_BYTES 1048576u
#define I2_CUE_MAX_DEPTH 256
#define I2_CUE_MAX_NODES 131072
#define I2_CUE_MAX_CELLS 65536
#define I2_CUE_MAX_BACKREFS 65536
#define I2_CUE_MAX_ATOM_BYTES 262144u
#define I2_CUE_MAX_TOTAL_ATOM_BYTES 1048576u
#define I2_CUE_MAX_WORK 2000000
#define I2_BSS_RESERVED_BYTES 33554432u
#define I2_BSS_ADMITTED_BYTES 25165824u
#define I2_HISTORICAL_REFUSAL_COUNT 2u

static const uint8_t I2_ADMISSION_ENVELOPE_DIGEST[32] = {
    0xd6, 0x74, 0xf3, 0xe8, 0xf6, 0x9c, 0xd5, 0x18,
    0xa4, 0x45, 0xa4, 0xde, 0xfc, 0x14, 0xff, 0x2c,
    0xe8, 0xd1, 0x57, 0x65, 0x40, 0x96, 0xc3, 0xbf,
    0x32, 0x0f, 0x1c, 0xbf, 0x95, 0xb6, 0x2b, 0xad
};

typedef struct {
    const char *catalog_id;
    const char *display_label;
    uint8_t program_hash[32];
    uint8_t executable_anchor[32];
    uint8_t pill_digest[32];
    uint8_t limits_hash[32];
    uint8_t capability_profile;
    uint8_t bootstrap;
    uint32_t pill_bytes;
} i2_admission_catalog_entry_t;
