#pragma once

/*
 * M24 has two named build-time targets.  This is a concrete platform seam,
 * not a runtime-discovered HAL: the image owns one console, one memory map,
 * one secondary-core policy, and (for qemu-virt) one virtio-mmio device.
 */
#if defined(TRINITITE_PLATFORM_QEMU_VIRT)
#define PLATFORM_NAME "qemu-virt"
#define PLATFORM_DRAM_BASE 0x40000000ULL
#define PLATFORM_UART_BASE 0x09000000ULL
#define PLATFORM_VIRTIO_MMIO_BASE 0x0A003E00ULL /* QEMU virt slot 31 */
#define PLATFORM_HAS_RPI_SPIN_TABLE 0
#define PLATFORM_NCORES 1
#else
#define PLATFORM_NAME "rpi4b"
#define PLATFORM_DRAM_BASE 0x00000000ULL
#define PLATFORM_UART_BASE 0xFE201000ULL
#define PLATFORM_VIRTIO_MMIO_BASE 0ULL
#define PLATFORM_HAS_RPI_SPIN_TABLE 1
#define PLATFORM_NCORES 4
#endif

#define PLATFORM_UART_DR (PLATFORM_UART_BASE + 0x00ULL)
#define PLATFORM_UART_FR (PLATFORM_UART_BASE + 0x18ULL)

#define PLATFORM_BSS_BASE (PLATFORM_DRAM_BASE + 0x08000000ULL)
#define PLATFORM_FORTH_BASE (PLATFORM_DRAM_BASE + 0x00100000ULL)
#define PLATFORM_ARENA_BASE (PLATFORM_DRAM_BASE + 0x00490000ULL)
#define PLATFORM_HEAP_BASE (PLATFORM_DRAM_BASE + 0x02490000ULL)
#define PLATFORM_ATOM_INDEX_BASE (PLATFORM_DRAM_BASE + 0x06490000ULL)
#define PLATFORM_ATOM_DATA_BASE (PLATFORM_DRAM_BASE + 0x06590000ULL)
#define PLATFORM_PILL_BASE (PLATFORM_DRAM_BASE + 0x10000000ULL)
#define PLATFORM_PILL_SCRATCH_BASE (PLATFORM_DRAM_BASE + 0x07900000ULL)
#define PLATFORM_UART_RXBUF_BASE (PLATFORM_DRAM_BASE + 0x000F8000ULL)
#define PLATFORM_COLD_BASE (PLATFORM_DRAM_BASE + 0x07100000ULL)
#define PLATFORM_CUE_RUB_SCRATCH (PLATFORM_DRAM_BASE + 0x0C000000ULL)
#define PLATFORM_CUE_CACHE_BASE (PLATFORM_DRAM_BASE + 0x0A000000ULL)

#define PLATFORM_CORE0_STACK_BASE (PLATFORM_DRAM_BASE + 0x00040000ULL)
#define PLATFORM_CORE0_STACK_TOP (PLATFORM_DRAM_BASE + 0x00080000ULL)
#define PLATFORM_CORE1_STACK_TOP (PLATFORM_DRAM_BASE + 0x07004000ULL)
#define PLATFORM_CORE2_STACK_TOP (PLATFORM_DRAM_BASE + 0x07008000ULL)
#define PLATFORM_CORE3_STACK_TOP (PLATFORM_DRAM_BASE + 0x0700C000ULL)

/* M24's one fixed virtio-mmio profile. */
#define PLATFORM_VIRTIO_MMIO_QUEUE_COUNT 2u
#define PLATFORM_VIRTIO_MMIO_QUEUE_SIZE 8u
#define PLATFORM_NATIVE_MTU 2048u
